# This is a CloudFormation template for Advanced Networking chapter 10 exercises
# 10.1 Create a basic VPC with a minimal script and no parameters
# 10.2 Modifying the original to include a subnet
# 10.3 Add parameters for the VPC and Subnet CIDR blocks
# 10.6 Adding a comment and will see if the AWS CodePipeline is automatically triggered. 
#      Changing the default settings for the CIDR blocks to verify execution. 

AWSTemplateFormatVersion: '2010-09-09'

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label: 
        default: Network
      Parameters:
        - VpcCidr
        - PublicSubnet0Cidr

    ParameterLabels:
      VpcCidr:
        default: VPC CIDR Block
      PublicSubnet0Cidr:
        default: Public Subnet 0  

Parameters: 
  VpcCidr: 
    Type: String
    Default: 10.15.0.0/16  
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PublicSubnet0Cidr:
    Type: String
    Default: 10.15.0.0/24  
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: false
      EnableDnsHostnames: false
      InstanceTenancy: dedicated
      Tags:
      - Key: Name
        Value: "VPC for Advanced Networking Exercise Chapter 10.1"
      - Key: Description
        Value: "Basic VPC without any subnets."

  PublicSubnet0:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-1a
      CidrBlock: !Ref PublicSubnet0Cidr
      MapPublicIpOnLaunch: true
      Tags: 
      - Key: Name
        Value: advanced-networking-chapter10-public-1a
      - Key: Description
        Value: "my public subnet"
      VpcId: !Ref myVPC
